services:
  users_db:
    image: postgres:17.5
    ports:
      - "5440:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    volumes:
      - users_data:/var/lib/postgresql/data/
    container_name: users_db
    restart: unless-stopped
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  session_store:
    image: redis:7.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    container_name: redis_sessions
    networks:
      - auth-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data

  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: auth:latest
    container_name: auth_rs
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    networks:
      - auth-network
    restart: unless-stopped
    depends_on:
      users_db:
        condition: service_healthy
      session_store:
        condition: service_started
    ports:
      - "8010:3000"
      - "8011:3001"

networks:
  auth-network:
    driver: bridge
  public-gateway-network:
    name: public-gateway-network
    external: true

volumes:
  users_data:
  redis_data:
